plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

run {
    standardInput = System.in
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    testLogging {
        // Show standard out and standard error logs in the console
        showStandardStreams = true
    }
}

jacocoTestReport {
    dependsOn test

    reports {
        xml.required = true
        html.required = true
    }
    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it, exclude: [
                'org/example/package/Main.class'
        ])
    }))
}

application {
    mainClass = 'org.example.Main'
}